spring.application.name=simplyfly



# DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/simplyflydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hari@2004



#hibernate settings
spring.jpa.hibernate.ddl-auto=update